### PR TITLE
fix typos, and windows specific nodes

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
@taxus13 fixed

What do you guys think about the stuff in CONTRIBUTING.md?

**Comment by sebastianrakel** [comment]
the name of the vm uuid column shouldn't be uuid

**Comment by bastelfreak** [comment]
which name do you suggest?

**Comment by sebastianrakel** [comment]
vm_uuid, because uuid is in some dbms registered as method

**Comment by bastelfreak** [comment]
@sebastianrakel fixed

**Comment by bastelfreak** [comment]
discussed on IRC, got ack

**Pull request merged**
