### PR TITLE
add ad note about density

### PR DESCRIPTION
**Pull request by bastelfreak**
please review

### CODE REVIEW

**Comment by taxus13** [comment]
"QEMU with KVM is very effizient." I think, this is too German ;)

**Comment by sebastianrakel** [comment]
"my computer engineering studying, I created a draft for an API. This draft is available at"
... much me and i for a team of developer...

**Comment by bastelfreak** [comment]
fixed the mentioned issue from @taxus13, lowered the VM amount after a conversation with foxxx0

**Comment by bastelfreak** [comment]
did a rebase, ack?

**Comment by sebastianrakel** [comment]
ack

**Comment by Bluewind** [comment]
ack

**Comment by bastelfreak** [comment]
merge after rebase

**Pull request merged**
