### PR TITLE
correction of german readme

### PR DESCRIPTION
**Pull request by taxus13**

### CODE REVIEW

**Comment by bastelfreak** [comment]
ack, anybody else who wants to review this?

**Comment by bastelfreak** [comment]
please add the following missing headline (use cases):
Übersicht aller Hypervisor + deren unterstützte Techniken

please update the path to the ERD:
https://rawgit.com/virtapi/virtapi/master/database/images/virtapi.svg

**Comment by bastelfreak** [comment]
"Zur Kommunikation läuft auf jeder VM ein Agent, der" that is wrong, the agent is running on the node, not in the VM.

**Comment by bastelfreak** [comment]
you can add yourself to the contributors list

**Comment by sebastianrakel** [comment]
change the inline erd graphic to a normal url with relative path.

**Comment by taxus13** [comment]
I fixed some problems, but somehow  the link  to "Übersicht aller Hypervisor und deren unterstützte Techniken" does not work. maybe somebody can review that issue

**Comment by sebastianrakel** [comment]
ack

**Comment by bastelfreak** [comment]
ack

**Pull request merged**
